Error on EmployeeUI.cs
Error messages as shown below:
Severity Code Description Project File Line Suppression State
Error CS0029 Cannot implicitly convert type 'string' to 'int' ConsoleApp2 C:\Users\iuxda\source\repos\ConsoleApp2\ConsoleApp2\UI\EmployeeUI.cs 22 Active
Error CS0029 Cannot implicitly convert type 'string' to 'int' ConsoleApp2 C:\Users\iuxda\source\repos\ConsoleApp2\ConsoleApp2\UI\EmployeeUI.cs 25 Active
Error CS0266 Cannot implicitly convert type 'decimal' to 'int'. An explicit conversion exists (are you missing a cast?) ConsoleApp2 C:\Users\iuxda\source\repos\ConsoleApp2\ConsoleApp2\UI\EmployeeUI.cs 28 Active
Error CS0029 Cannot implicitly convert type 'string' to 'int' ConsoleApp2 C:\Users\iuxda\source\repos\ConsoleApp2\ConsoleApp2\UI\EmployeeUI.cs 31 Active